#---------------Set min delay for data latch
set_min_delay -from [get_cells FirstStage/req_latch] -to [get_cells Interface_dw/req_latch] 1.6079999999999999


#Fix Data_latch nets

#Data[0]
set_property BEL SLICEL.AFF [get_cells FirstStage/genblk1[0].Data_latch] 
set_property LOC SLICE_X37Y75 [get_cells FirstStage/genblk1[0].Data_latch] 
set_property BEL SLICEL.AFF [get_cells Interface_dw/genblk1[0].Data_latch] 
set_property LOC SLICE_X43Y75 [get_cells Interface_dw/genblk1[0].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_L_AQ CLBLL_LOGIC_OUTS0 EE2BEG0 NE2BEG0 SL1BEG0 BYP_ALT0 BYP0 CLBLM_L_AX }  } [get_nets Interface_dw/Data_up_i[0]] 

#Data[1]
set_property BEL SLICEL.BFF [get_cells FirstStage/genblk1[1].Data_latch] 
set_property LOC SLICE_X37Y75 [get_cells FirstStage/genblk1[1].Data_latch] 
set_property BEL SLICEL.BFF [get_cells Interface_dw/genblk1[1].Data_latch] 
set_property LOC SLICE_X43Y75 [get_cells Interface_dw/genblk1[1].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_L_BQ CLBLL_LOGIC_OUTS1 EE4BEG1 WR1BEG2 BYP_ALT5 BYP5 CLBLM_L_BX }  } [get_nets Interface_dw/Data_up_i[1]] 

#Data[2]
set_property BEL SLICEL.CFF [get_cells FirstStage/genblk1[2].Data_latch] 
set_property LOC SLICE_X37Y75 [get_cells FirstStage/genblk1[2].Data_latch] 
set_property BEL SLICEL.CFF [get_cells Interface_dw/genblk1[2].Data_latch] 
set_property LOC SLICE_X43Y75 [get_cells Interface_dw/genblk1[2].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_L_CQ CLBLL_LOGIC_OUTS2 EE2BEG2 NE2BEG2 SL1BEG2 BYP_ALT2 BYP2 CLBLM_L_CX }  } [get_nets Interface_dw/Data_up_i[2]] 

#Data[3]
set_property BEL SLICEL.DFF [get_cells FirstStage/genblk1[3].Data_latch] 
set_property LOC SLICE_X37Y75 [get_cells FirstStage/genblk1[3].Data_latch] 
set_property BEL SLICEL.DFF [get_cells Interface_dw/genblk1[3].Data_latch] 
set_property LOC SLICE_X43Y75 [get_cells Interface_dw/genblk1[3].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_L_DQ CLBLL_LOGIC_OUTS3 EE2BEG3 NE2BEG3 SL1BEG3 BYP_ALT7 BYP7 CLBLM_L_DX }  } [get_nets Interface_dw/Data_up_i[3]] 

#Data[4]
set_property BEL SLICEL.AFF [get_cells FirstStage/genblk1[4].Data_latch] 
set_property LOC SLICE_X37Y76 [get_cells FirstStage/genblk1[4].Data_latch] 
set_property BEL SLICEL.AFF [get_cells Interface_dw/genblk1[4].Data_latch] 
set_property LOC SLICE_X43Y76 [get_cells Interface_dw/genblk1[4].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_L_AQ CLBLL_LOGIC_OUTS0 EE2BEG0 NE2BEG0 SL1BEG0 BYP_ALT0 BYP0 CLBLM_L_AX }  } [get_nets Interface_dw/Data_up_i[4]] 

#Data[5]
set_property BEL SLICEL.BFF [get_cells FirstStage/genblk1[5].Data_latch] 
set_property LOC SLICE_X37Y76 [get_cells FirstStage/genblk1[5].Data_latch] 
set_property BEL SLICEL.BFF [get_cells Interface_dw/genblk1[5].Data_latch] 
set_property LOC SLICE_X43Y76 [get_cells Interface_dw/genblk1[5].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_L_BQ CLBLL_LOGIC_OUTS1 EE4BEG1 WR1BEG2 BYP_ALT5 BYP5 CLBLM_L_BX }  } [get_nets Interface_dw/Data_up_i[5]] 

#Data[6]
set_property BEL SLICEL.CFF [get_cells FirstStage/genblk1[6].Data_latch] 
set_property LOC SLICE_X37Y76 [get_cells FirstStage/genblk1[6].Data_latch] 
set_property BEL SLICEL.CFF [get_cells Interface_dw/genblk1[6].Data_latch] 
set_property LOC SLICE_X43Y76 [get_cells Interface_dw/genblk1[6].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_L_CQ CLBLL_LOGIC_OUTS2 EE2BEG2 NE2BEG2 SL1BEG2 BYP_ALT2 BYP2 CLBLM_L_CX }  } [get_nets Interface_dw/Data_up_i[6]] 

#Data[7]
set_property BEL SLICEL.DFF [get_cells FirstStage/genblk1[7].Data_latch] 
set_property LOC SLICE_X37Y76 [get_cells FirstStage/genblk1[7].Data_latch] 
set_property BEL SLICEL.DFF [get_cells Interface_dw/genblk1[7].Data_latch] 
set_property LOC SLICE_X43Y76 [get_cells Interface_dw/genblk1[7].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_L_DQ CLBLL_LOGIC_OUTS3 EE4BEG3 WR1BEG_S0 BYP_ALT7 BYP7 CLBLM_L_DX }  } [get_nets Interface_dw/Data_up_i[7]] 

#Data[8]
set_property BEL SLICEL.BFF [get_cells FirstStage/genblk1[8].Data_latch] 
set_property LOC SLICE_X36Y75 [get_cells FirstStage/genblk1[8].Data_latch] 
set_property BEL SLICEM.BFF [get_cells Interface_dw/genblk1[8].Data_latch] 
set_property LOC SLICE_X42Y75 [get_cells Interface_dw/genblk1[8].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_LL_BQ CLBLL_LOGIC_OUTS5 EE2BEG1 NE2BEG1 SL1BEG1 BYP_ALT4 BYP4 CLBLM_M_BX }  } [get_nets Interface_dw/Data_up_i[8]] 

#Data[9]
set_property BEL SLICEL.CFF [get_cells FirstStage/genblk1[9].Data_latch] 
set_property LOC SLICE_X36Y75 [get_cells FirstStage/genblk1[9].Data_latch] 
set_property BEL SLICEM.CFF [get_cells Interface_dw/genblk1[9].Data_latch] 
set_property LOC SLICE_X42Y75 [get_cells Interface_dw/genblk1[9].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_LL_CQ CLBLL_LOGIC_OUTS6 EE4BEG2 WR1BEG3 BYP_ALT3 BYP3 CLBLM_M_CX }  } [get_nets Interface_dw/Data_up_i[9]] 

#Data[10]
set_property BEL SLICEL.AFF [get_cells FirstStage/genblk1[10].Data_latch] 
set_property LOC SLICE_X36Y75 [get_cells FirstStage/genblk1[10].Data_latch] 
set_property BEL SLICEM.AFF [get_cells Interface_dw/genblk1[10].Data_latch] 
set_property LOC SLICE_X42Y75 [get_cells Interface_dw/genblk1[10].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_LL_AQ CLBLL_LOGIC_OUTS4 EE4BEG0 WR1BEG1 BYP_ALT1 BYP1 CLBLM_M_AX }  } [get_nets Interface_dw/Data_up_i[10]] 

#Data[11]
set_property BEL SLICEL.AFF [get_cells FirstStage/genblk1[11].Data_latch] 
set_property LOC SLICE_X36Y74 [get_cells FirstStage/genblk1[11].Data_latch] 
set_property BEL SLICEM.AFF [get_cells Interface_dw/genblk1[11].Data_latch] 
set_property LOC SLICE_X42Y74 [get_cells Interface_dw/genblk1[11].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_LL_AQ CLBLL_LOGIC_OUTS4 EE4BEG0 WR1BEG1 BYP_ALT1 BYP1 CLBLM_M_AX }  } [get_nets Interface_dw/Data_up_i[11]] 

#Data[12]
set_property BEL SLICEL.AFF [get_cells FirstStage/genblk1[12].Data_latch] 
set_property LOC SLICE_X36Y76 [get_cells FirstStage/genblk1[12].Data_latch] 
set_property BEL SLICEM.AFF [get_cells Interface_dw/genblk1[12].Data_latch] 
set_property LOC SLICE_X42Y76 [get_cells Interface_dw/genblk1[12].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_LL_AQ CLBLL_LOGIC_OUTS4 EE4BEG0 WR1BEG1 BYP_ALT1 BYP1 CLBLM_M_AX }  } [get_nets Interface_dw/Data_up_i[12]] 

#Data[13]
set_property BEL SLICEL.BFF [get_cells FirstStage/genblk1[13].Data_latch] 
set_property LOC SLICE_X36Y76 [get_cells FirstStage/genblk1[13].Data_latch] 
set_property BEL SLICEM.BFF [get_cells Interface_dw/genblk1[13].Data_latch] 
set_property LOC SLICE_X42Y76 [get_cells Interface_dw/genblk1[13].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_LL_BQ CLBLL_LOGIC_OUTS5 EE2BEG1 NE2BEG1 SL1BEG1 BYP_ALT4 BYP4 CLBLM_M_BX }  } [get_nets Interface_dw/Data_up_i[13]] 

#Data[14]
set_property BEL SLICEL.CFF [get_cells FirstStage/genblk1[14].Data_latch] 
set_property LOC SLICE_X36Y76 [get_cells FirstStage/genblk1[14].Data_latch] 
set_property BEL SLICEM.CFF [get_cells Interface_dw/genblk1[14].Data_latch] 
set_property LOC SLICE_X42Y76 [get_cells Interface_dw/genblk1[14].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_LL_CQ CLBLL_LOGIC_OUTS6 EE4BEG2 WR1BEG3 BYP_ALT3 BYP3 CLBLM_M_CX }  } [get_nets Interface_dw/Data_up_i[14]] 

#Data[15]
set_property BEL SLICEL.DFF [get_cells FirstStage/genblk1[15].Data_latch] 
set_property LOC SLICE_X36Y76 [get_cells FirstStage/genblk1[15].Data_latch] 
set_property BEL SLICEM.DFF [get_cells Interface_dw/genblk1[15].Data_latch] 
set_property LOC SLICE_X42Y76 [get_cells Interface_dw/genblk1[15].Data_latch] 
set_property FIXED_ROUTE { { CLBLL_LL_DQ CLBLL_LOGIC_OUTS7 EE2BEG3 NE2BEG3 SL1BEG3 BYP_ALT6 BYP6 CLBLM_M_DX }  } [get_nets Interface_dw/Data_up_i[15]] 
