set_max_delay -from [get_pins Stadio_1/req_latch/G] -to [get_pins Stadio_1/*.Data_latch/GE] 3.3653000000000004
set_max_delay -from [get_pins Stadio_1/req_latch/G] -to [get_pins Stadio_1/req_latch/GE] 2.4490000000000003
set_min_delay -through [get_pins Stadio_1/Ack_up_o] 0.597
set_max_delay -through [get_pins Stadio_1/Ack_up_o] 2.9539000000000004
set_max_delay -from [get_pins Stadio_2/req_latch/G] -to [get_pins Stadio_2/*.Data_latch/GE] 3.1739
set_max_delay -from [get_pins Stadio_2/req_latch/G] -to [get_pins Stadio_2/req_latch/GE] 2.3445000000000005
set_min_delay -through [get_pins Stadio_2/Ack_up_o] 0.12
set_max_delay -through [get_pins Stadio_2/Ack_up_o] 2.5942000000000003
set_max_delay -from [get_pins Stadio_3/req_latch/G] -to [get_pins Stadio_3/*.Data_latch/GE] 2.6833000000000005
set_max_delay -from [get_pins Stadio_3/req_latch/G] -to [get_pins Stadio_3/req_latch/GE] 2.4611000000000005
set_min_delay -through [get_pins Stadio_3/Ack_up_o] -0.21599999999999997
set_max_delay -through [get_pins Stadio_3/Ack_up_o] 2.1685
#---------------Set min delay for data latch from Stadio_1 to Stadio_2
set_min_delay -from [get_pins Stadio_1/req_latch/G] -to [get_pins Stadio_2/req_latch/D] 0.869
set_max_delay -from [get_pins Stadio_1/req_latch/G] -to [get_pins Stadio_2/req_latch/D] 3.400


#Fix Data_latch nets from Stadio_1 to Stadio_2


set_property BEL AFF [get_cells {Stadio_1/genblk1[22].Data_latch}]
set_property BEL AFF [get_cells {Stadio_1/genblk1[28].Data_latch}]
set_property BEL BFF [get_cells {Stadio_1/genblk1[29].Data_latch}]
set_property BEL CFF [get_cells {Stadio_1/genblk1[30].Data_latch}]
set_property BEL DFF [get_cells {Stadio_1/genblk1[31].Data_latch}]
set_property BEL AFF [get_cells {Stadio_1/genblk1[0].Data_latch}]
set_property BEL BFF [get_cells {Stadio_1/genblk1[7].Data_latch}]
set_property BEL CFF [get_cells {Stadio_1/genblk1[8].Data_latch}]
set_property BEL AFF [get_cells {Stadio_1/genblk1[16].Data_latch}]
set_property BEL BFF [get_cells {Stadio_1/genblk1[17].Data_latch}]
set_property BEL CFF [get_cells {Stadio_1/genblk1[18].Data_latch}]
set_property BEL DFF [get_cells {Stadio_1/genblk1[6].Data_latch}]
set_property BEL AFF [get_cells {Stadio_1/genblk1[24].Data_latch}]
set_property BEL BFF [get_cells {Stadio_1/genblk1[25].Data_latch}]
set_property BEL CFF [get_cells {Stadio_1/genblk1[26].Data_latch}]
set_property BEL DFF [get_cells {Stadio_1/genblk1[27].Data_latch}]
set_property BEL AFF [get_cells {Stadio_1/genblk1[13].Data_latch}]
set_property BEL BFF [get_cells {Stadio_1/genblk1[14].Data_latch}]
set_property BEL CFF [get_cells {Stadio_1/genblk1[15].Data_latch}]
set_property BEL DFF [get_cells {Stadio_1/genblk1[23].Data_latch}]
set_property BEL AFF [get_cells {Stadio_1/genblk1[2].Data_latch}]
set_property BEL BFF [get_cells {Stadio_1/genblk1[3].Data_latch}]
set_property BEL CFF [get_cells {Stadio_1/genblk1[4].Data_latch}]
set_property BEL DFF [get_cells {Stadio_1/genblk1[5].Data_latch}]
set_property BEL AFF [get_cells {Stadio_1/genblk1[10].Data_latch}]
set_property BEL BFF [get_cells {Stadio_1/genblk1[11].Data_latch}]
set_property BEL CFF [get_cells {Stadio_1/genblk1[12].Data_latch}]
set_property BEL DFF [get_cells {Stadio_1/genblk1[9].Data_latch}]
set_property BEL AFF [get_cells {Stadio_1/genblk1[19].Data_latch}]
set_property BEL BFF [get_cells {Stadio_1/genblk1[1].Data_latch}]
set_property BEL CFF [get_cells {Stadio_1/genblk1[20].Data_latch}]
set_property BEL DFF [get_cells {Stadio_1/genblk1[21].Data_latch}]
set_property LOC SLICE_X36Y73 [get_cells {Stadio_1/genblk1[22].Data_latch}]
set_property LOC SLICE_X36Y74 [get_cells {Stadio_1/genblk1[28].Data_latch}]
set_property LOC SLICE_X36Y74 [get_cells {Stadio_1/genblk1[29].Data_latch}]
set_property LOC SLICE_X36Y74 [get_cells {Stadio_1/genblk1[30].Data_latch}]
set_property LOC SLICE_X36Y74 [get_cells {Stadio_1/genblk1[31].Data_latch}]
set_property LOC SLICE_X36Y75 [get_cells {Stadio_1/genblk1[0].Data_latch}]
set_property LOC SLICE_X36Y75 [get_cells {Stadio_1/genblk1[7].Data_latch}]
set_property LOC SLICE_X36Y75 [get_cells {Stadio_1/genblk1[8].Data_latch}]
set_property LOC SLICE_X37Y73 [get_cells {Stadio_1/genblk1[16].Data_latch}]
set_property LOC SLICE_X37Y73 [get_cells {Stadio_1/genblk1[17].Data_latch}]
set_property LOC SLICE_X37Y73 [get_cells {Stadio_1/genblk1[18].Data_latch}]
set_property LOC SLICE_X37Y73 [get_cells {Stadio_1/genblk1[6].Data_latch}]
set_property LOC SLICE_X37Y74 [get_cells {Stadio_1/genblk1[24].Data_latch}]
set_property LOC SLICE_X37Y74 [get_cells {Stadio_1/genblk1[25].Data_latch}]
set_property LOC SLICE_X37Y74 [get_cells {Stadio_1/genblk1[26].Data_latch}]
set_property LOC SLICE_X37Y74 [get_cells {Stadio_1/genblk1[27].Data_latch}]
set_property LOC SLICE_X37Y75 [get_cells {Stadio_1/genblk1[13].Data_latch}]
set_property LOC SLICE_X37Y75 [get_cells {Stadio_1/genblk1[14].Data_latch}]
set_property LOC SLICE_X37Y75 [get_cells {Stadio_1/genblk1[15].Data_latch}]
set_property LOC SLICE_X37Y75 [get_cells {Stadio_1/genblk1[23].Data_latch}]
set_property LOC SLICE_X38Y73 [get_cells {Stadio_1/genblk1[2].Data_latch}]
set_property LOC SLICE_X38Y73 [get_cells {Stadio_1/genblk1[3].Data_latch}]
set_property LOC SLICE_X38Y73 [get_cells {Stadio_1/genblk1[4].Data_latch}]
set_property LOC SLICE_X38Y73 [get_cells {Stadio_1/genblk1[5].Data_latch}]
set_property LOC SLICE_X38Y74 [get_cells {Stadio_1/genblk1[10].Data_latch}]
set_property LOC SLICE_X38Y74 [get_cells {Stadio_1/genblk1[11].Data_latch}]
set_property LOC SLICE_X38Y74 [get_cells {Stadio_1/genblk1[12].Data_latch}]
set_property LOC SLICE_X38Y74 [get_cells {Stadio_1/genblk1[9].Data_latch}]
set_property LOC SLICE_X39Y73 [get_cells {Stadio_1/genblk1[19].Data_latch}]
set_property LOC SLICE_X39Y73 [get_cells {Stadio_1/genblk1[1].Data_latch}]
set_property LOC SLICE_X39Y73 [get_cells {Stadio_1/genblk1[20].Data_latch}]
set_property LOC SLICE_X39Y73 [get_cells {Stadio_1/genblk1[21].Data_latch}]


#---------------Set min delay for data latch from Stadio_2 to Stadio_3
set_min_delay -from [get_pins Stadio_2/req_latch/G] -to [get_pins Stadio_3/req_latch/D] 0.823
set_max_delay -from [get_pins Stadio_2/req_latch/G] -to [get_pins Stadio_3/req_latch/D] 3.206


#Fix Data_latch nets from Stadio_2 to Stadio_3


set_property BEL CFF [get_cells {Stadio_2/genblk1[8].Data_latch}]
set_property BEL AFF [get_cells {Stadio_2/genblk1[28].Data_latch}]
set_property BEL BFF [get_cells {Stadio_2/genblk1[29].Data_latch}]
set_property BEL CFF [get_cells {Stadio_2/genblk1[30].Data_latch}]
set_property BEL DFF [get_cells {Stadio_2/genblk1[31].Data_latch}]
set_property BEL AFF [get_cells {Stadio_2/genblk1[0].Data_latch}]
set_property BEL BFF [get_cells {Stadio_2/genblk1[7].Data_latch}]
set_property BEL AFF [get_cells {Stadio_2/genblk1[22].Data_latch}]
set_property BEL AFF [get_cells {Stadio_2/genblk1[16].Data_latch}]
set_property BEL BFF [get_cells {Stadio_2/genblk1[17].Data_latch}]
set_property BEL CFF [get_cells {Stadio_2/genblk1[18].Data_latch}]
set_property BEL DFF [get_cells {Stadio_2/genblk1[6].Data_latch}]
set_property BEL AFF [get_cells {Stadio_2/genblk1[24].Data_latch}]
set_property BEL BFF [get_cells {Stadio_2/genblk1[25].Data_latch}]
set_property BEL CFF [get_cells {Stadio_2/genblk1[26].Data_latch}]
set_property BEL DFF [get_cells {Stadio_2/genblk1[27].Data_latch}]
set_property BEL AFF [get_cells {Stadio_2/genblk1[13].Data_latch}]
set_property BEL BFF [get_cells {Stadio_2/genblk1[14].Data_latch}]
set_property BEL CFF [get_cells {Stadio_2/genblk1[15].Data_latch}]
set_property BEL DFF [get_cells {Stadio_2/genblk1[23].Data_latch}]
set_property BEL AFF [get_cells {Stadio_2/genblk1[2].Data_latch}]
set_property BEL BFF [get_cells {Stadio_2/genblk1[3].Data_latch}]
set_property BEL CFF [get_cells {Stadio_2/genblk1[4].Data_latch}]
set_property BEL DFF [get_cells {Stadio_2/genblk1[5].Data_latch}]
set_property BEL AFF [get_cells {Stadio_2/genblk1[10].Data_latch}]
set_property BEL BFF [get_cells {Stadio_2/genblk1[11].Data_latch}]
set_property BEL CFF [get_cells {Stadio_2/genblk1[12].Data_latch}]
set_property BEL DFF [get_cells {Stadio_2/genblk1[9].Data_latch}]
set_property BEL AFF [get_cells {Stadio_2/genblk1[19].Data_latch}]
set_property BEL BFF [get_cells {Stadio_2/genblk1[1].Data_latch}]
set_property BEL CFF [get_cells {Stadio_2/genblk1[20].Data_latch}]
set_property BEL DFF [get_cells {Stadio_2/genblk1[21].Data_latch}]
set_property LOC SLICE_X39Y76 [get_cells {Stadio_2/genblk1[8].Data_latch}]
set_property LOC SLICE_X39Y75 [get_cells {Stadio_2/genblk1[28].Data_latch}]
set_property LOC SLICE_X39Y75 [get_cells {Stadio_2/genblk1[29].Data_latch}]
set_property LOC SLICE_X39Y75 [get_cells {Stadio_2/genblk1[30].Data_latch}]
set_property LOC SLICE_X39Y75 [get_cells {Stadio_2/genblk1[31].Data_latch}]
set_property LOC SLICE_X39Y76 [get_cells {Stadio_2/genblk1[0].Data_latch}]
set_property LOC SLICE_X39Y76 [get_cells {Stadio_2/genblk1[7].Data_latch}]
set_property LOC SLICE_X39Y74 [get_cells {Stadio_2/genblk1[22].Data_latch}]
set_property LOC SLICE_X40Y74 [get_cells {Stadio_2/genblk1[16].Data_latch}]
set_property LOC SLICE_X40Y74 [get_cells {Stadio_2/genblk1[17].Data_latch}]
set_property LOC SLICE_X40Y74 [get_cells {Stadio_2/genblk1[18].Data_latch}]
set_property LOC SLICE_X40Y74 [get_cells {Stadio_2/genblk1[6].Data_latch}]
set_property LOC SLICE_X40Y75 [get_cells {Stadio_2/genblk1[24].Data_latch}]
set_property LOC SLICE_X40Y75 [get_cells {Stadio_2/genblk1[25].Data_latch}]
set_property LOC SLICE_X40Y75 [get_cells {Stadio_2/genblk1[26].Data_latch}]
set_property LOC SLICE_X40Y75 [get_cells {Stadio_2/genblk1[27].Data_latch}]
set_property LOC SLICE_X40Y76 [get_cells {Stadio_2/genblk1[13].Data_latch}]
set_property LOC SLICE_X40Y76 [get_cells {Stadio_2/genblk1[14].Data_latch}]
set_property LOC SLICE_X40Y76 [get_cells {Stadio_2/genblk1[15].Data_latch}]
set_property LOC SLICE_X40Y76 [get_cells {Stadio_2/genblk1[23].Data_latch}]
set_property LOC SLICE_X41Y74 [get_cells {Stadio_2/genblk1[2].Data_latch}]
set_property LOC SLICE_X41Y74 [get_cells {Stadio_2/genblk1[3].Data_latch}]
set_property LOC SLICE_X41Y74 [get_cells {Stadio_2/genblk1[4].Data_latch}]
set_property LOC SLICE_X41Y74 [get_cells {Stadio_2/genblk1[5].Data_latch}]
set_property LOC SLICE_X41Y75 [get_cells {Stadio_2/genblk1[10].Data_latch}]
set_property LOC SLICE_X41Y75 [get_cells {Stadio_2/genblk1[11].Data_latch}]
set_property LOC SLICE_X41Y75 [get_cells {Stadio_2/genblk1[12].Data_latch}]
set_property LOC SLICE_X41Y75 [get_cells {Stadio_2/genblk1[9].Data_latch}]
set_property LOC SLICE_X42Y74 [get_cells {Stadio_2/genblk1[19].Data_latch}]
set_property LOC SLICE_X42Y74 [get_cells {Stadio_2/genblk1[1].Data_latch}]
set_property LOC SLICE_X42Y74 [get_cells {Stadio_2/genblk1[20].Data_latch}]
set_property LOC SLICE_X42Y74 [get_cells {Stadio_2/genblk1[21].Data_latch}]
set_property BEL CFF [get_cells {Stadio_3/genblk1[8].Data_latch}]
set_property BEL AFF [get_cells {Stadio_3/genblk1[28].Data_latch}]
set_property BEL BFF [get_cells {Stadio_3/genblk1[29].Data_latch}]
set_property BEL CFF [get_cells {Stadio_3/genblk1[30].Data_latch}]
set_property BEL DFF [get_cells {Stadio_3/genblk1[31].Data_latch}]
set_property BEL AFF [get_cells {Stadio_3/genblk1[0].Data_latch}]
set_property BEL BFF [get_cells {Stadio_3/genblk1[7].Data_latch}]
set_property BEL AFF [get_cells {Stadio_3/genblk1[22].Data_latch}]
set_property BEL AFF [get_cells {Stadio_3/genblk1[16].Data_latch}]
set_property BEL BFF [get_cells {Stadio_3/genblk1[17].Data_latch}]
set_property BEL CFF [get_cells {Stadio_3/genblk1[18].Data_latch}]
set_property BEL DFF [get_cells {Stadio_3/genblk1[6].Data_latch}]
set_property BEL AFF [get_cells {Stadio_3/genblk1[24].Data_latch}]
set_property BEL BFF [get_cells {Stadio_3/genblk1[25].Data_latch}]
set_property BEL CFF [get_cells {Stadio_3/genblk1[26].Data_latch}]
set_property BEL DFF [get_cells {Stadio_3/genblk1[27].Data_latch}]
set_property BEL AFF [get_cells {Stadio_3/genblk1[13].Data_latch}]
set_property BEL BFF [get_cells {Stadio_3/genblk1[14].Data_latch}]
set_property BEL CFF [get_cells {Stadio_3/genblk1[15].Data_latch}]
set_property BEL DFF [get_cells {Stadio_3/genblk1[23].Data_latch}]
set_property BEL AFF [get_cells {Stadio_3/genblk1[2].Data_latch}]
set_property BEL BFF [get_cells {Stadio_3/genblk1[3].Data_latch}]
set_property BEL CFF [get_cells {Stadio_3/genblk1[4].Data_latch}]
set_property BEL DFF [get_cells {Stadio_3/genblk1[5].Data_latch}]
set_property BEL AFF [get_cells {Stadio_3/genblk1[10].Data_latch}]
set_property BEL BFF [get_cells {Stadio_3/genblk1[11].Data_latch}]
set_property BEL CFF [get_cells {Stadio_3/genblk1[12].Data_latch}]
set_property BEL DFF [get_cells {Stadio_3/genblk1[9].Data_latch}]
set_property BEL AFF [get_cells {Stadio_3/genblk1[19].Data_latch}]
set_property BEL BFF [get_cells {Stadio_3/genblk1[1].Data_latch}]
set_property BEL CFF [get_cells {Stadio_3/genblk1[20].Data_latch}]
set_property BEL DFF [get_cells {Stadio_3/genblk1[21].Data_latch}]
set_property LOC SLICE_X43Y75 [get_cells {Stadio_3/genblk1[8].Data_latch}]
set_property LOC SLICE_X43Y74 [get_cells {Stadio_3/genblk1[28].Data_latch}]
set_property LOC SLICE_X43Y74 [get_cells {Stadio_3/genblk1[29].Data_latch}]
set_property LOC SLICE_X43Y74 [get_cells {Stadio_3/genblk1[30].Data_latch}]
set_property LOC SLICE_X43Y74 [get_cells {Stadio_3/genblk1[31].Data_latch}]
set_property LOC SLICE_X43Y75 [get_cells {Stadio_3/genblk1[0].Data_latch}]
set_property LOC SLICE_X43Y75 [get_cells {Stadio_3/genblk1[7].Data_latch}]
set_property LOC SLICE_X43Y73 [get_cells {Stadio_3/genblk1[22].Data_latch}]
set_property LOC SLICE_X44Y73 [get_cells {Stadio_3/genblk1[16].Data_latch}]
set_property LOC SLICE_X44Y73 [get_cells {Stadio_3/genblk1[17].Data_latch}]
set_property LOC SLICE_X44Y73 [get_cells {Stadio_3/genblk1[18].Data_latch}]
set_property LOC SLICE_X44Y73 [get_cells {Stadio_3/genblk1[6].Data_latch}]
set_property LOC SLICE_X44Y74 [get_cells {Stadio_3/genblk1[24].Data_latch}]
set_property LOC SLICE_X44Y74 [get_cells {Stadio_3/genblk1[25].Data_latch}]
set_property LOC SLICE_X44Y74 [get_cells {Stadio_3/genblk1[26].Data_latch}]
set_property LOC SLICE_X44Y74 [get_cells {Stadio_3/genblk1[27].Data_latch}]
set_property LOC SLICE_X44Y75 [get_cells {Stadio_3/genblk1[13].Data_latch}]
set_property LOC SLICE_X44Y75 [get_cells {Stadio_3/genblk1[14].Data_latch}]
set_property LOC SLICE_X44Y75 [get_cells {Stadio_3/genblk1[15].Data_latch}]
set_property LOC SLICE_X44Y75 [get_cells {Stadio_3/genblk1[23].Data_latch}]
set_property LOC SLICE_X45Y73 [get_cells {Stadio_3/genblk1[2].Data_latch}]
set_property LOC SLICE_X45Y73 [get_cells {Stadio_3/genblk1[3].Data_latch}]
set_property LOC SLICE_X45Y73 [get_cells {Stadio_3/genblk1[4].Data_latch}]
set_property LOC SLICE_X45Y73 [get_cells {Stadio_3/genblk1[5].Data_latch}]
set_property LOC SLICE_X45Y74 [get_cells {Stadio_3/genblk1[10].Data_latch}]
set_property LOC SLICE_X45Y74 [get_cells {Stadio_3/genblk1[11].Data_latch}]
set_property LOC SLICE_X45Y74 [get_cells {Stadio_3/genblk1[12].Data_latch}]
set_property LOC SLICE_X45Y74 [get_cells {Stadio_3/genblk1[9].Data_latch}]
set_property LOC SLICE_X46Y73 [get_cells {Stadio_3/genblk1[19].Data_latch}]
set_property LOC SLICE_X46Y73 [get_cells {Stadio_3/genblk1[1].Data_latch}]
set_property LOC SLICE_X46Y73 [get_cells {Stadio_3/genblk1[20].Data_latch}]
set_property LOC SLICE_X46Y73 [get_cells {Stadio_3/genblk1[21].Data_latch}]
